fix(NullTransport): missing addressFamily
> Unhandled Error
> Traceback (most recent call last):
>   File "twisted/python/log.py", line 96, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "twisted/python/log.py", line 80, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "twisted/python/context.py", line 117, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "twisted/python/context.py", line 82, in callWithContext
>     return func(*args, **kw)
> --- <exception caught here> ---
>   File "twisted/internet/posixbase.py", line 487, in _doReadOrWrite
>     why = selectable.doRead()
>   File "twisted/internet/tcp.py", line 248, in doRead
>     return self._dataReceived(data)
>   File "twisted/internet/tcp.py", line 253, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "vncdotool/loggingproxy.py", line 208, in dataReceived
>     RFBServer.dataReceived(self, data)
>   File "vncdotool/loggingproxy.py", line 44, in dataReceived
>     self._handler[0]()
>   File "vncdotool/loggingproxy.py", line 213, in _handle_clientInit
>     self.peer.startLogging(self)
>   File "vncdotool/loggingproxy.py", line 167, in startLogging
>     self.vnclog.connectionMade()
>   File "vncdotool/client.py", line 150, in connectionMade
>     if self.transport.addressFamily == socket.AF_INET:
> builtins.AttributeError: 'NullTransport' object has no attribute 'addressFamily'