Improve Pixelformat handling (#243)
* fix(rfb): Encoding.lookup() for signed32

Encodings are defined using both (un-)signed-int32. Internally they are
converted to s32. Do the same when doing the lookup.

Fixes: 3dacd57f1d2dbd1bb5009a2429a9a582ab5136c5

* fix(client): PSEUDO_COLOR image format

The "Cursor Pseudo-encoding" uses the same pixel format as the regular
FB_UPDATE. The previous code assumed the hard-coded 32-bit RGBX format,
which lead to `Image.frombytes()` expecting more data than available if
only 24 bits-per-pixel are used.

Test setup:
  /tmp/vncdo/libvncserver-LibVNCServer-0.9.14/examples/pnmshow24 /usr/lib/x86_64-linux-gnu/perl5/5.32/Tk/demos/images/teapot.ppm
  vnclog -vvv -s localhost:0 /tmp/log
  gvncviewer localhost:2

> Traceback (most recent call last):
>   File "twisted/python/log.py", line 96, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "twisted/python/log.py", line 80, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "twisted/python/context.py", line 117, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "twisted/python/context.py", line 82, in callWithContext
>     return func(*args, **kw)
> --- <exception caught here> ---
>   File "twisted/internet/posixbase.py", line 487, in _doReadOrWrite
>     why = selectable.doRead()
>   File "twisted/internet/tcp.py", line 248, in doRead
>     return self._dataReceived(data)
>   File "twisted/internet/tcp.py", line 253, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "vncdotool/loggingproxy.py", line 245, in dataReceived
>     self.vnclog.dataReceived(data)
>   File "vncdotool/rfb.py", line 1108, in dataReceived
>     self._handler()
>   File "vncdotool/rfb.py", line 1117, in _handleExpected
>     self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
>   File "vncdotool/rfb.py", line 1083, in _handleDecodePsuedoCursor
>     self.updateCursor(x, y, width, height, image, mask)
>   File "vncdotool/client.py", line 454, in updateCursor
>     self.cursor = Image.frombytes('RGBX', (width, height), image)
>   File "PIL/Image.py", line 2882, in frombytes
>     im.frombytes(data, decoder_name, args)
>   File "PIL/Image.py", line 815, in frombytes
>     raise ValueError("not enough image data")
> builtins.ValueError: not enough image data

<https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#cursor-pseudo-encoding>

* fix(proxy): NullTransport.loseConnection() WIP

TODO: Defining this method is not enough, the command "loseConnection"
must also result in terminating the (other) connections and the process
itself.

> Traceback (most recent call last):
>   File "twisted/python/log.py", line 96, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "twisted/python/log.py", line 80, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "twisted/python/context.py", line 117, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "twisted/python/context.py", line 82, in callWithContext
>     return func(*args, **kw)
> --- <exception caught here> ---
>   File "twisted/internet/posixbase.py", line 487, in _doReadOrWrite
>     why = selectable.doRead()
>   File "twisted/internet/tcp.py", line 248, in doRead
>     return self._dataReceived(data)
>   File "twisted/internet/tcp.py", line 253, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "/vncdotool/loggingproxy.py", line 245, in dataReceived
>     self.vnclog.dataReceived(data)
>   File "/vncdotool/rfb.py", line 1108, in dataReceived
>     self._handler()
>   File "/vncdotool/rfb.py", line 1117, in _handleExpected
>     self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
>   File "/vncdotool/rfb.py", line 691, in _handleRectangle
>     self.transport.loseConnection()
> builtins.AttributeError: 'NullTransport' object has no attribute 'loseConnection'

* refactor(rfb): integer math to calculate bitmap size

<https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#cursor-pseudo-encoding>

* refactor(rfb): Introduce Dataclass for PixelFormat

<https://www.rfc-editor.org/rfc/rfc6143#section-7.4>

* refactor: Use Dataclass PixelFormat

Move all state variables related to PixelFormat into its own instance
and pass those around.

Rename {set -> select}ImageMode() to better describe its semantic:
Either we accept the native encoding the server has proposed during the
initial handshake, or we ask the server to switch to our preferred
encoding, which is BGR;16 for Apple Remote Desktop servers or RGBX
otherwise.

Change unit tests to use a valid INIT sequence.

Fix `test_vncConnectionMade` as `clientConnectionMade` is now called
regularly because of this.
> Traceback (most recent call last):
>   File "tests/unit/test_client.py", line 34, in test_vncConnectionMade
>     factory.clientConnectionMade.assert_called_once_with(cli)
>   File "unittest/mock.py", line 918, in assert_called_once_with
>     raise AssertionError(msg)
> AssertionError: Expected 'clientConnectionMade' to be called once. Called 2 times.

Closes #205

* fix(proxy): More logging

Fixes: 3dacd57f1d2dbd1bb5009a2429a9a582ab5136c5