fix(VNCDoToolFactory): missing pseudodesktop
> CRITICAL:twisted:Unhandled Error
> Traceback (most recent call last):
>   File "twisted/python/log.py", line 96, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "twisted/python/log.py", line 80, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "twisted/python/context.py", line 117, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "twisted/python/context.py", line 82, in callWithContext
>     return func(*args, **kw)
> --- <exception caught here> ---
>   File "twisted/internet/posixbase.py", line 487, in _doReadOrWrite
>     why = selectable.doRead()
>   File "twisted/internet/tcp.py", line 248, in doRead
>     return self._dataReceived(data)
>   File "twisted/internet/tcp.py", line 253, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "vncdotool/loggingproxy.py", line 177, in dataReceived
>     self.vnclog.dataReceived(data)
>   File "vncdotool/rfb.py", line 833, in dataReceived
>     self._handler()
>   File "vncdotool/rfb.py", line 842, in _handleExpected
>     self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
>   File "vncdotool/rfb.py", line 371, in _handleServerName
>     self.vncConnectionMade()
>   File "vncdotool/client.py", line 392, in vncConnectionMade
>     if self.factory.pseudodesktop:
> builtins.AttributeError: 'VNCLoggingServerFactory' object has no attribute 'pseudodesktop'