fix(rfb): DecodeHextileSubrectsColoured
bytes[index] returns int already, no need to use ord() anymore:
> TypeError: ord() expected string of length 1, but int found