refactor: Use Dataclass PixelFormat
Move all state variables related to PixelFormat into its own instance
and pass those around.

Rename {set -> select}ImageMode() to better describe its semantic:
Either we accept the native encoding the server has proposed during the
initial handshake, or we ask the server to switch to our preferred
encoding, which is BGR;16 for Apple Remote Desktop servers or RGBX
otherwise.

Change unit tests to use a valid INIT sequence.

Fix `test_vncConnectionMade` as `clientConnectionMade` is now called
regularly because of this.
> Traceback (most recent call last):
>   File "tests/unit/test_client.py", line 34, in test_vncConnectionMade
>     factory.clientConnectionMade.assert_called_once_with(cli)
>   File "unittest/mock.py", line 918, in assert_called_once_with
>     raise AssertionError(msg)
> AssertionError: Expected 'clientConnectionMade' to be called once. Called 2 times.

Closes #205